# Generated by Django 3.1 on 2020-08-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('money', models.CharField(max_length=200)),
                ('one_line', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='image/elly.png', null=True, upload_to='image')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('seller', models.TextField()),
                ('content', models.TextField()),
                ('content_list', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('like_num', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
