# Generated by Django 3.1 on 2020-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='motive',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='money',
            new_name='motiveSum',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='one_line',
            new_name='strengthSum',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='subjectSum',
        ),
        migrations.AddField(
            model_name='blog',
            name='sellerStory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='strength',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subject',
            field=models.TextField(null=True),
        ),
    ]
