# Generated by Django 3.0.8 on 2020-08-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_auto_20200828_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='motive',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='motiveSum',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='strengthSum',
            new_name='one_line',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subjectSum',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='sellerStory',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='subject',
        ),
    ]
