# Generated by Django 3.1 on 2021-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20200828_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_spec1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_spec2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_subject1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_subject2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_why1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pdf_why2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='seller_comment',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='seller_num',
            field=models.TextField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='blog',
            name='seller_spec',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='seller_story',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content_list',
            field=models.TextField(default=''),
        ),
    ]
