# Generated by Django 3.1 on 2021-03-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0004_auto_20210323_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='실무', max_length=20),
        ),
    ]
