# Generated by Django 2.2.4 on 2019-10-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0003_auto_20191021_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
