# Generated by Django 2.2.4 on 2019-11-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0005_board_win_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='win_score',
            field=models.IntegerField(default=2),
        ),
    ]
