# Generated by Django 2.2.4 on 2019-11-11 14:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0006_auto_20191111_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ratings_down',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='ratings_up',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_commentlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_boardlist',
            field=models.ManyToManyField(blank=True, related_name='user_boardlist', to='MECboard.Board'),
        ),
        migrations.CreateModel(
            name='Finished_board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('board_idx', models.IntegerField()),
                ('comment_writer', models.CharField(max_length=50)),
                ('comment_content', models.TextField()),
                ('comment_post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vote', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media/images')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MECboard.Profile')),
            ],
        ),
    ]
