# Generated by Django 2.2.4 on 2019-11-14 05:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0007_auto_20191111_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_board',
            name='board_idx',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='comment_content',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='comment_post_date',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='comment_writer',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='image',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='finished_board',
            name='vote',
        ),
        migrations.AddField(
            model_name='finished_board',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='finished_board',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='media/thumbnail'),
        ),
        migrations.AddField(
            model_name='finished_board',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='finished_board',
            name='writer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finished_board',
            name='idx',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Finished_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('board_idx', models.IntegerField()),
                ('writer', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('vote', models.IntegerField()),
                ('rating', models.IntegerField(default=0)),
                ('image', models.ImageField(default='media/default.jpg', upload_to='media/images')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MECboard.Profile')),
            ],
        ),
    ]
