# Generated by Django 2.2.4 on 2019-12-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0011_profile_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_authenticated',
        ),
    ]
