# Generated by Django 2.2.4 on 2020-03-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0012_remove_profile_is_authenticated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_boardlist',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_commentlist',
            field=models.ManyToManyField(blank=True, related_name='user_commentlist', to='MECboard.Comment'),
        ),
    ]
