# Generated by Django 3.0.8 on 2020-07-20 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0014_comment_writer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_commentlist',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_likelist',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
