# Generated by Django 3.0.8 on 2020-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('money', models.CharField(max_length=200)),
                ('one_line', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('seller', models.TextField()),
                ('content', models.TextField()),
                ('content_list', models.TextField()),
            ],
        ),
    ]
