# Generated by Django 3.0.8 on 2020-08-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='a',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='b',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='c',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='d',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='e',
        ),
    ]
