# Generated by Django 3.0.8 on 2020-08-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
