# Generated by Django 3.0.6 on 2020-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='like_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
