# Generated by Django 2.2.4 on 2019-12-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0009_auto_20191114_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finished_comment',
            name='profile',
        ),
        migrations.AddField(
            model_name='board',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Finished_board',
        ),
        migrations.DeleteModel(
            name='Finished_comment',
        ),
    ]
