# Generated by Django 2.2.4 on 2019-12-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MECboard', '0010_auto_20191218_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_authenticated',
            field=models.BooleanField(null=True),
        ),
    ]
