# Generated by Django 3.1 on 2020-09-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20200828_1700'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, default='image/elly.png', null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_postlist',
            field=models.ManyToManyField(blank=True, related_name='user_commentlist', to='writing.Blog'),
        ),
    ]
