# Generated by Django 3.1 on 2020-09-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200903_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, default='image/elly.png', null=True, upload_to='image/profile'),
        ),
    ]
