# Generated by Django 3.1 on 2020-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_auto_20200828_1700'),
        ('login', '0004_auto_20200905_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='account',
            name='own_blog',
        ),
        migrations.AddField(
            model_name='account',
            name='user_purchase_list',
            field=models.ManyToManyField(blank=True, related_name='user_purchase_list', to='writing.Blog'),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_photo',
            field=models.ImageField(blank=True, default='image/elly.png', upload_to='image/profile'),
        ),
    ]
