# Generated by Django 3.1 on 2020-09-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200915_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='introduction',
            field=models.TextField(blank=True, max_length='100'),
        ),
    ]
